### ISSUE TITLE
Function config - write current values first to plugins.ini, as other plugins do

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_font_preview#2]

**Comment by Alexey-T** [comment]
Maybe you write config before the func 'config'? Too early!

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_font_preview/commit/4eee1085f166bc1debe7c596547efeb5493b01cc

**Comment by Alexey-T** [comment]
` if file_ext in self.opts['file_exts']:`

if right part is 'ext1,ext2,ext3' this is bad!
must be:
` if file_ext in self.opts['file_exts'].split(','):`

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_font_preview/commit/8c5095f9a9c8949102e515c4c2e1d85f3b15402d
