### ISSUE TITLE
How En users can avoid fish-local lines in different lang? 

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_font_preview#9]
Maybe to solve it, you should make 2 template files - with fish-local and pure En.

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_font_preview/commit/47b80c6c262e259a44f2b25357146e9a864beddd

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_font_preview/commit/5f2a7c0e329887213dc7e940bbcfa2f201fcd6ee
